export const TRIGGER_LOADING = "product/TRIGGER_LOADING";
export const FETCH_PRODUCTS = "product/FETCH_PRODUCTS";
export const RECEIVE_PRODUCTS_SUCCESS = "product/RECEIVE_PRODUCTS_SUCCESS";
export const RECEIVE_PRODUCTS_FAILURE = "product/RECEIVE_PRODUCTS_FAILURE";
