export const TRIGGER_LOADING = 'products/TRIGGER_LOADING';
export const FETCH_PRODUCTS = 'products/FETCH_PRODUCTS';
export const RECEIVE_PRODUCTS_SUCCESS = 'products/RECEIVE_PRODUCTS_SUCCESS';
export const RECEIVE_PRODUCTS_FAILURE = 'products/RECEIVE_PRODUCTS_FAILURE';

export const SELECT_PRODUCT = 'product/SELECT_PRODUCT';
export const TRIGGER_PRODUCT_LOADING = 'product/TRIGGER_LOADING';
export const FETCH_PRODUCT = 'product/FETCH_PRODUCT';
export const DATA_REQUESTED = 'product/DATA_REQUESTED';
export const RECEIVE_PRODUCT_SUCCESS = 'product/RECEIVE_PRODUCT_SUCCESS';
export const RECEIVE_PRODUCT_FAILURE = 'product/RECEIVE_PRODUCT_FAILURE';
